#!/usr/bin/env bash
#using the previous exercise command, write a script that displays lines containing the "#bash" word, thus allowing you to easily get the PID of your Bash process.

ps -e f | grep "bash"
