#!/usr/bin/env bash
#displays numbers from 1 to 100
#displays FizzBuzz when number is a multiple of  3 and 5
#displays Fizz when number is a multiple of 3
#displays Buzz when number is a multiple of 5
#otherwise displays the number in list format

for i in {1..100}; 
do
	if [ $((i % 5 == 0)) ] && [ $((i % 3)) ];
then 
echo "FizzBuzz";
elif [ $((i % 3 == 0)) ];
then 
echo "Fizz"
elif [ $((i % 5 == 0)) ];
then 
echo "Buzz"
else echo $i
fi
done
