#!/usr/bin/env bash
#script loops from 1 to 10 and prints a loop that displays "bad luck" for the 4th loop 
#iteration, "good luck" for the 8th loop iteration and  "Best School" for all other 
#iterations
count=1
while [ $count -le 10 ] 
do 
if [ $count = 4 ]
then echo "bad luck"
elif [ $count = 8 ] 
then echo "good luck"
else echo "Best School"
fi
((count++))
done
