#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes:
#displays hours from 0 to 12
#displays minutes from 1 to 59
#uses the while loop
hours=0
minutes=1
while [ $hours -le 12 ]
do echo "Hour: $hours"
((hours++))
while [ $minutes -le 59 ]
do echo $minutes
((minutes++))
done
((minutes=1))
done
